print("")
print("")
print("Wellcome to JRNL scripting tool")
print("")
print("")
print("************************************************")
print("******************MENU**************************")
print("************************************************")
print("")
print("")
print("Local Jornal")
print("Network Jornal")
print("")
print("")
